edit_mode = "vi"
prompt = "echo $(starship prompt)"
startup = [
  "alias icat = kitty +kitten icat",
  "config set env.SHELL $nu.env._",
  "config set env.STARSHIP_CONFIG $(echo $nu.env.HOME .dots/starship.toml | str collect '/')",
  ]

[env]
STARSHIP_SHELL = "nu"
COLORTERM = "truecolor"
FZF_DEFAULT_COMMAND = "rg --files --hidden --follow --glob \"!.git/*\""
LANG = "en_GB.UTF-8"
