edit_mode = "vi"
prompt = "echo $(starship prompt)"
startup = [
  "alias now [] { date format \"%Y-%m-%dT%H:%M%z\" }",
  "alias icat [pth] { kitty +kitten icat $pth }",
  "config set env.SHELL $nu.env._",
  "config set env.STARSHIP_SHELL $nu.env._",
  "config set env.STARSHIP_CONFIG $(echo $nu.env.HOME .dots/starship.toml | str collect '/')",
  ]

[env]
COLORTERM = "truecolor"
FZF_DEFAULT_COMMAND = "rg --files --hidden --follow --glob \"!.git/*\""
LANG = "en_GB.UTF-8"
