"$schema" = "https://starship.rs/config-schema.json"

format = """
$env_var\
$directory\
$git_branch\
$git_commit\
$git_state\
$hg_branch\
$nix_shell\
$line_break\
$character"""

[character]
success_symbol = "[•](bold green)"
error_symbol = "[?](bold red)"
vimcmd_symbol = "[N](bold green)"
vimcmd_replace_one_symbol = "[R](bold pink)"
vimcmd_replace_symbol = "[R](bold pink)"
vimcmd_visual_symbol = "[V](bold yellow)"

[env_var.STARSHIP_SHELL]
default = "???"
format = "[$env_value]($style) "
style = "bold purple"

[git_branch]
format = "[$branch]($style) "
style = "bold yellow"

[hg_branch]
format = "[hg~$branch]($style) "
style = "bold #ff69b4"

[nix_shell]
format = '[nix~$state(\($name\))]($style)'

[custom]

[custom.tab]
description = "The current tab in the tab terminal multiplexer"
command = "tab --starship"
when = "tab --starship"
shell = ["sh"]
format = "[$output]($style) "
style = "bold blue"
