# Testing oh-my-zsh (https://github.com/robbyrussell/oh-my-zsh)

# Global Order: zshenv, zprofile, zshrc, zlogin

ZSH=$HOME/.dots/zsh

ZSH_THEME="spoon"
# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-extras bundler tmux rvm ruby debian thor ssh-agent redis-cli gem colorize command-not-found vi-mode zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
READNULLCMD=${PAGER:-/usr/bin/pager}

setopt histignorealldups sharehistory
setopt extendedglob
#setopt interactivecomments

export GEMEDITOR="vim"
export EDITOR="vim"

bindkey -v
bindkey -M vicmd v edit-command-line

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

