#!/usr/bin/env bash

set -o vi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export GEMEDITOR='vim'
export EDITOR='vim'

# alias electron='/Applications/Electron.app/Contents/MacOS/Electron'
alias irb='irb --readline -r irb/completion -r rubygems'
# alias ls='ls -hFG'
alias ls=exa
alias scannet='arp -i en0 -a'
alias serve='devd .'
# alias serve='python -m SimpleHTTPServer'
alias ssh='TERM=xterm ssh'
alias vault='vim /Volumes/vault/asiches/management/data/info.ttl'
# alias gpg='gpg2'


###############################################################################
# Paths
###############################################################################
# JAVA_HOME=$(/usr/libexec/java_home)
# export JAVA_HOME


# export RUST_PATH="$HOME/.cargo/bin"
# export RUST_SRC_PATH="$HOME/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/"
#export SYSROOT=/path/to/rustc/sysroot cargo install clippy

### Added by the Heroku Toolbelt
# export HEROKU_PATH='/usr/local/heroku/bin'

OPENSSL_PATH='/usr/local/opt/openssl'
export OPENSSL_INCLUDE_DIR=$OPENSSL_PATH/include
export OPENSSL_LIB_DIR=$OPENSSL_PATH/lib

export LOCAL_PATH=$HOME/bin
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"

export PATH="$PATH:/usr/local/bin:/usr/local/sbin"
export PATH="$PATH:$LOCAL_PATH"
export PATH="$PATH:$GOBIN"
export PATH="$PATH:$HEROKU_PATH"
export PATH="$PATH:$JAVA_HOME/bin"
export PATH="$PATH:$RUST_PATH"
# export PATH="$HOME/.cargo/bin:$PATH"
# shellcheck source=/dev/null
source ~/.cargo/env

export MANPATH=/usr/local/man:$MANPATH


###############################################################################
# Sources
###############################################################################

# shellcheck source=/dev/null
source "$HOME/.dots/bash/ps1.sh"
# shellcheck source=/dev/null
source "$HOME/.dots/bash/docker.sh"
# shellcheck source=/dev/null
source "$HOME/.dots/bash/secrets"

# shellcheck source=/dev/null
[ -f /usr/local/etc/bash_completion.d/git-completion.bash ] && source /usr/local/etc/bash_completion.d/git-completion.bash
# shellcheck source=/dev/null
[ -f /usr/local/etc/bash_completion.d/tmux ] && source /usr/local/etc/bash_completion.d/tmux
# shellcheck source=/dev/null
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
alias fess='fzf --bind "enter:execute(less {})"'

git_branch() {
  git rev-parse --abbrev-ref HEAD 2>/dev/null
}

# shellcheck source=/dev/null
source "$HOME/.opam/opam-init/init.sh" > /dev/null 2> /dev/null || true
