#!/usr/bin/env bash

set -o vi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export GEMEDITOR='vim'
export EDITOR='vim'

# alias electron='/Applications/Electron.app/Contents/MacOS/Electron'
alias irb='irb --readline -r irb/completion -r rubygems'
# alias ls='ls -hFG'
alias ls=exa
alias tree2='exa -Tl'
alias scannet='arp -i en0 -a'
alias serve='devd .'
# alias serve='python -m SimpleHTTPServer'
alias ssh='TERM=xterm ssh'
alias cellar='cd ~/kitchen/cellar'
alias weeknum='date +%V'
# alias gpg='gpg2'
alias pasifae='PASSWORD_STORE_DIR=/keybase/team/pasifae/.pasifae-store pass'

###############################################################################
# Paths
###############################################################################
# JAVA_HOME=$(/usr/libexec/java_home)
# export JAVA_HOME

### Added by the Heroku Toolbelt
# export HEROKU_PATH='/usr/local/heroku/bin'

OPENSSL_PATH='/usr/local/opt/openssl'
export OPENSSL_INCLUDE_DIR=$OPENSSL_PATH/include
export OPENSSL_LIB_DIR=$OPENSSL_PATH/lib

export LOCAL_PATH=$HOME/bin
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"

export PATH="$PATH:/usr/local/bin:/usr/local/sbin"
export PATH="$PATH:$LOCAL_PATH:$HOME/Library/Python/3.7/bin"
export PATH="$PATH:$HOME/.cabal/bin"
export PATH="$PATH:$GOBIN"
export PATH="$PATH:$HEROKU_PATH"
export PATH="$PATH:$JAVA_HOME/bin"
# shellcheck source=/dev/null
source ~/.cargo/env

export MANPATH=/usr/local/man:$MANPATH

# SQLite installed via brew
export PATH="/usr/local/opt/sqlite/bin:$PATH"

[ -d /usr/local/opt/grep/libexec/gnubin ] && PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"

###############################################################################
# Sources
###############################################################################

# shellcheck source=/dev/null
source "$HOME/.dots/bash/ps1.sh"
# shellcheck source=/dev/null
source "$HOME/.dots/bash/docker.sh"
# shellcheck source=/dev/null

# shellcheck source=/dev/null
[ -f /usr/local/etc/bash_completion.d/git-completion.bash ] && source /usr/local/etc/bash_completion.d/git-completion.bash
# shellcheck source=/dev/null
[ -f /usr/local/etc/bash_completion.d/tmux ] && source /usr/local/etc/bash_completion.d/tmux
# shellcheck source=/dev/null
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
alias fess='fzf --bind "enter:execute(less {})"'

# Wasmer
export WASMER_DIR="$HOME/.wasmer"
# shellcheck source=/dev/null
[ -s "$WASMER_DIR/wasmer.sh" ] && source "$WASMER_DIR/wasmer.sh"  # This loads wasmer

# shellcheck source=/dev/null
source "$HOME/.dots/bash/opam.sh"

# bash 3 [ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
# shellcheck source=/dev/null
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

if [ -e ~/.nix-profile/etc/profile.d/nix.sh ]; then . ~/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
